#!/usr/bin/env bash
# generate_cf_ip_allowlist.sh — Fetch Cloudflare's published IP ranges and
# emit an Apache .htaccess fragment that restricts origin access to those
# ranges only. Part of issue #33 (origin lockdown, Phase 5).
#
# Usage:
#   ./scripts/generate_cf_ip_allowlist.sh                    # print to stdout
#   ./scripts/generate_cf_ip_allowlist.sh --output .htaccess.cf-allow  # write to file
#
# The generated fragment uses mod_authz_host (Apache 2.4) Require ip
# directives, which natively support CIDR notation for both IPv4 and IPv6.
#
# IMPORTANT: This script does NOT modify .htaccess directly. It generates
# a fragment you must review and manually include. Enabling the allow-list
# without testing can take the site offline if Cloudflare's ranges change
# or if the deploy path (rsync/scp) depends on HTTP access to the origin.
set -euo pipefail

VERBOSE=false
DEBUG=false

log_v() { [[ "$VERBOSE" == true ]] && echo "[verbose] $*" >&2; }
log_d() { [[ "$DEBUG" == true ]] && echo "[debug] $*" >&2; }

show_help() {
    cat << 'HELP'
generate_cf_ip_allowlist.sh — Fetch Cloudflare's published IP ranges and
emit an Apache .htaccess fragment that restricts origin access to those
ranges only. Part of issue #33 (origin lockdown, Phase 5).

Usage:
  ./scripts/generate_cf_ip_allowlist.sh                    # print to stdout
  ./scripts/generate_cf_ip_allowlist.sh --output .htaccess.cf-allow  # write to file

Standard flags:
  -h, --help     Show this help message and exit
  -v, --verbose  Show verbose log messages
  -d, --debug    Enable bash trace (set -x)

Options:
  --output FILE  Write the generated fragment to FILE instead of stdout

The generated fragment uses mod_authz_host (Apache 2.4) Require ip
directives, which natively support CIDR notation for both IPv4 and IPv6.

IMPORTANT: This script does NOT modify .htaccess directly. It generates
a fragment you must review and manually include. Enabling the allow-list
without testing can take the site offline if Cloudflare's ranges change
or if the deploy path (rsync/scp) depends on HTTP access to the origin.
HELP
}

die_usage() {
    echo "Error: $*" >&2
    echo "" >&2
    show_help >&2
    exit 1
}

# Pre-parse standard flags (-h/-v/-d)
_remaining_args=()
for _arg in "$@"; do
    case "$_arg" in
        -h|--help)    show_help; exit 0 ;;
        -v|--verbose) VERBOSE=true ;;
        -d|--debug)   DEBUG=true; set -x ;;
        *)            _remaining_args+=("$_arg") ;;
    esac
done
set -- "${_remaining_args[@]}"
unset _arg _remaining_args

OUTPUT_FILE=""
if [[ "${1:-}" == "--output" ]]; then
  OUTPUT_FILE="${2:?--output requires a file path}"
elif [[ $# -gt 0 ]]; then
  die_usage "unrecognized argument: $1"
fi

CF_IPV4_URL="https://www.cloudflare.com/ips-v4"
CF_IPV6_URL="https://www.cloudflare.com/ips-v6"

log_v "Fetching Cloudflare IP ranges from $CF_IPV4_URL and $CF_IPV6_URL"
echo "Fetching Cloudflare IP ranges..." >&2
IPV4=$(curl -sS --fail "$CF_IPV4_URL" || echo "")
IPV6=$(curl -sS --fail "$CF_IPV6_URL" || echo "")

if [[ -z "$IPV4" && -z "$IPV6" ]]; then
  echo "ERROR: Could not fetch Cloudflare IP ranges. Aborting." >&2
  exit 1
fi

generate() {
  local out="$1"
  {
    echo "# ── Cloudflare origin IP allow-list (issue #33) ──────────────────────────"
    echo "# Generated by scripts/generate_cf_ip_allowlist.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "#"
    echo "# This block restricts HTTP/HTTPS access to the origin to Cloudflare's"
    echo "# published IP ranges. Direct access to the origin IP (bypassing"
    echo "# Cloudflare's WAF/DDoS protection) is denied with a 403."
    echo "#"
    echo "# Uses mod_authz_host (Apache 2.4) Require ip — supports CIDR natively."
    echo "#"
    echo "# PREREQUISITES before enabling:"
    echo "#   1. Test that the deploy path (rsync/scp via sync.sh) does NOT use"
    echo "#      HTTP — it uses SSH, so it should be unaffected."
    echo "#   2. Verify cPanel/SSH access ports (2083, 2096, 22) are NOT gated"
    echo "#      by this .htaccess (they use separate ports, not port 80/443)."
    echo "#   3. Keep a backup of .htaccess before enabling — a stale IP list"
    echo "#      can take the site offline."
    echo "#   4. Set up a monthly cron to re-run generate_cf_ip_allowlist.sh"
    echo "#      and review the diff (Cloudflare's ranges change)."
    echo "#"
    echo "# To ENABLE: Uncomment the <RequireAll> block below."
    echo "# To DISABLE: Comment it out or remove this block."
    echo ""
    echo "#<RequireAll>"
    echo "#  Require all denied"
    echo "#  # IPv4 allow-list ($(echo "$IPV4" | wc -w) ranges)"

    for ip in $IPV4; do
      echo "#  Require ip $ip"
    done

    echo "#  # IPv6 allow-list ($(echo "$IPV6" | wc -w) ranges)"

    for ip in $IPV6; do
      echo "#  Require ip $ip"
    done

    echo "#</RequireAll>"
    echo ""
    echo "# ── End Cloudflare origin IP allow-list ────────────────────────────────"
    echo ""
  } > "$out"
}

if [[ -n "$OUTPUT_FILE" ]]; then
  generate "$OUTPUT_FILE"
  echo "Written to $OUTPUT_FILE ($(wc -l < "$OUTPUT_FILE") lines)" >&2
  echo "Review the file, then manually include it in .htaccess when ready." >&2
else
  generate /dev/stdout
fi
